import { Product } from "./Product";

export const ListOfProducts: Product[] = [
    {
        _id: 1,
        Name: "Electric Planer Brandix KL370090G 300 Watts",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "749.98" },
        Meta: { Availability: "In Stock" },
        Colors: ["yellow"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-1.jpg"],
        Section:["FeaturedProducts"],
        Category:"Power Tools"
    },
    {
        _id: 2,
        Name: "Undefined Tool IRadix DPS3000SY 2700 Watts",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "1019.99" },
        Meta: { Availability: "Out of Stock",Brand:"Wakita" },
        Colors: ["yellow","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-2.jpg"],
        Section:["FeaturedProducts"],
        Category:"Hand Tools"
    },
    {
        _id: 3,
        Name: "Drill Screwdriver Brandix ALX7054 200 Watts",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "850.70" },
        Meta: { Availability: "In Stock",Brand:"Wakita"  },
        Colors: ["blue","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-3.jpg"],
        cardBadge:"New",
        Section:["FeaturedProducts"],
        Category:"Power Tools"
    },
    {
        _id: 4,
        Name: "Drill Series 3 Brandix KSR4590PQS 1500 Watts",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "1189.30", SalesPrice: "949.00" },
        Meta: { Availability: "In Stock",Brand:"Wakita"  },
        Colors: ["blue","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-4.jpg"],
        cardBadge:"Sale",
        Section:["FeaturedProducts"],
        Category:"Power Tools"
    },
    {
        _id: 5,
        Name: "Brandix Router Power Tool 2017ERXPK",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "1700.00" },
        Meta: { Availability: "In Stock" ,Brand:"Wakita" },
        Colors: ["yellow","blue","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-5.jpg"],
        Section:["FeaturedProducts"],
        Category:"Power Tools"
    },
    {
        _id: 6,
        Name: "Brandix Drilling Machine DM2019KW4 4kW",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "3199.00" },
        Meta: { Availability: "In Stock",Brand:"Wakita"  },
        Colors: ["yellow","blue"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-6.jpg"],
        cardBadge:"Hot",
        Section:["FeaturedProducts"],
        Category:"Power Tools"
    },
    {
        _id: 7,
        Name: "Brandix Pliers",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "24.65" },
        Meta: { Availability: "In Stock",Brand:"Wakita"  },
        Colors: ["blue","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-7.jpg"],
        Section:["FeaturedProducts"],
        Category:"Power Tools"
    },
    {
        _id: 8,
        Name: "Water Hose 40cm",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "15.00" },
        Meta: { Availability: "In Stock",Brand:"Wakita"  },
        Colors: ["yellow","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-8.jpg"],
        Section:["FeaturedProducts"],
        Category:"Machine Tools"
    },
    {
        _id: 9,
        Name: "Brandix Air Compressor DELTAKX500",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "1800.00" },
        Meta: { Availability: "In Stock",Brand:"Wakita"  },
        Colors: ["yellow","blue","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["category-4.jpg"],
        Section:["BestSellers"],
        Category:"Power Tools"
    },
    {
        _id: 10,
        Name: "Hand Tool Kit",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "649.99" },
        Meta: { Availability: "In Stock" ,Brand:"Wakita" },
        Colors: ["yellow","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-11.jpg"],
        Section:["BestSellers"],
        Category:"Machine Tools"
    },
    {
        _id: 11,
        Name: "Brandix Angle Grinder KZX3890PQW",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "290.00" },
        Meta: { Availability: "In Stock",Brand:"Wakita"  },
        Colors: ["yellow","blue","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-12.jpg"],
        cardBadge:"Hot",
        Section:["BestSellers"],
        Category:"Power Tools"
    },
    {
        _id: 12,
        Name: "Brandix Screwdriver SCREW1500ACC",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "1499.00" },
        Meta: { Availability: "In Stock",Brand:"Wakita"  },
        Colors: ["blue","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-12.jpg"],
        Section:["None"],
        Category:"Machine Tools"
    },
    {
        _id: 13,
        Name: "Ash's Chainsaw 3.5kW",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "666.99" },
        Meta: { Availability: "In Stock",Brand:"Wakita" },
        Colors: ["yellow","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-13.jpg"],
        Section:["None"],
        Category:"Power Tools"
    },
    {
        _id: 14,
        Name: "Brandix Electric Jigsaw JIG7000BQ",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "149.00" },
        Meta: { Availability: "In Stock",Brand:"Wakita" },
        Colors: ["yellow","blue","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-14.jpg"],
        Section:["BestSellers"],
        Category:"Machine Tools"
    },
    {
        _id: 15,
        Name: "Brandix Screwdriver",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "170.00" },
        Meta: { Availability: "In Stock",Brand:"Wakita" },
        Colors: ["yellow","blue","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-15.jpg"],
        Section:["BestSellers"],
        Category:"Garden Equipment"
    },
    {
        _id: 16,
        Name: "Brandix Drilling Machine DM2019KW4",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "19.00" },
        Meta: { Availability: "In Stock",Brand:"Wakita" },
        Colors: ["yellow","blue","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["category-3.jpg"],
        cardBadge:"New",
        Section:["BestSellers"],
        Category:"Power Tools"
    },
    {
        _id: 17,
        Name: "Brandix Drilling Machine DM2019KW4 4kW",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "628.00" },
        Meta: { Availability: "In Stock",Brand:"Wakita" },
        Colors: ["blue","red"],
        Material: ["Metal","Plastic"],
        Gallery: ["product-9.jpg"],
        Section:["BestSellers"],
        Category:"Power Tools"
    },
    {
        _id: 18,
        Name: "Grinder Drilling Machine DM2019KW4",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "110.00" },
        Meta: { Availability: "In Stock",Brand:"Wakita" },
        Colors: ["yellow","blue","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-18.jpg"],
        cardBadge:"Hot",
        Section:["BestSellers"],
        Category:"Power Tools"
    },
    {
        _id: 19,
        Name: "Drill Series 3 Brandix KSR4590PQS 1500 Watts",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "457.00" },
        Meta: { Availability: "In Stock",Brand:"Wakita" },
        Colors: ["yellow","blue","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-19.jpg"],
        Section:["BestSellers"],
        Category:"Hand Tools"
    },
    {
        _id: 20,
        Name: "Brandix Angle Grinder KZX3890PQW",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "345.00" },
        Meta: { Availability: "In Stock",Brand:"Wakita" },
        Colors: ["yellow","blue","red"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-20.jpg"],
        Section:["FeaturedProducts"],
        Category:"Garden Equipment"
    },
    {
        _id: 21,
        Name: "Brandix Drilling Machine DM2019KW4",
        Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ornare, mi in ornare elementum, libero nibh lacinia urna, quis convallis lorem erat at purus. Maecenas eu varius nisi.",
        Price: { NormalPrice: "987.00" },
        Meta: { Availability: "In Stock",Brand:"Wakita" },
        Colors: ["yellow","blue"],
        Material: ["Metal","Wood","Plastic"],
        Gallery: ["product-21.jpg"],
        cardBadge:"New",
        Section:["FeaturedProducts"],
        Category:"Garden Equipment"
    }
]

